# Run acceptance-cycle on develop commits.
#
# Acceptance cycle comprises:
# - run tests on develop
# - release into main with bumped versions
#
name: Acceptance Cycle

on:
  push:
    branches:
      - develop

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Install trunk
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked trunk

      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Compile
        run: sbt clean compile

      - name: License Header Check
        run: sbt headerCheck

      - name: Test
        run: sbt test scripted

      - name: Documentation
        run: sbt doc

      - name: Publish Check
        run: |
          sbt publishLocal
          sbt publishM2

  release:
    needs: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Build
        run: |
          git config --global user.email "nigeleke@users.noreply.github.com"
          git config --global user.name "Nigel Eke"
          sbt "release with-defaults"
          export VERSION=$(git describe --abbrev=0 --tags)
          git checkout main
          git merge $VERSION
          git push