# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Compile, publish locally and test
        run: sbt clean compile publishM2 publishLocal

      - name: Check publication
        run: |
          echo "Hello world from inline script!"
          echo "This is my script, and I can put anything here."
          echo "I can even use bash commands like 'pwd':"
          pwd
          ls ~/.m2/repository/
          ls ~/.ivy2/local/
