# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Compile
        run: sbt clean compile

      - name: Check publication
        run: |
          pwd
          cd ~
          pwd
          cd /home/runner/work/sbt-rust/sbt-rust
          sbt publishM2 publishLocal 'show ivyPaths'
          ls -al ~
          ls -R ~/.m2
          ls -R ~/.ivy2
          ls -R /home/runner/work/sbt-rust/sbt-rust
