# Quick feedback for unit tests on non-main commits.
#
name: Commit Cycle

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install trunk
        run: cargo install --locked trunk

      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "sbt"

      - name: Compile
        run: sbt clean compile

      - name: Test instals
        run: |
          cargo --version
          trunk --version

      - name: Test cargo
        run: |
          cd src/sbt-test/sbt-rust/simple-cargo-new
          cargo build

      - name: Test
        run: sbt test scripted
